version: 1.0.{build}

image: Ubuntu1804

before_build:
  - git submodule update --init --recursive

install:
  - sh: sudo apt -y remove x264 libx264-dev
  - sh: sudo apt -y install build-essential checkinstall cmake pkg-config yasm
  - sh: sudo apt -y install git gfortran
  - sh: sudo apt -y install libjpeg8-dev libpng-dev 
  - sh: sudo apt -y install software-properties-common
  - sh: sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
  - sh: sudo apt -y update 
  - sh: sudo apt -y install libjasper1
  - sh: sudo apt -y install libtiff-dev 
  - sh: sudo apt -y install libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev
  - sh: sudo apt -y install libxine2-dev libv4l-dev
  - sh: cd /usr/include/linux
  - sh: sudo ln -s -f ../libv4l1-videodev.h videodev.h
  - sh: cd ~/
  - sh: sudo apt -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  - sh: sudo apt -y install libgtk2.0-dev libtbb-dev qt5-default
  - sh: sudo apt -y install libatlas-base-dev
  - sh: sudo apt -y install libfaac-dev libmp3lame-dev libtheora-dev
  - sh: sudo apt -y install libvorbis-dev libxvidcore-dev
  - sh: sudo apt -y install libopencore-amrnb-dev libopencore-amrwb-dev
  - sh: sudo apt -y install libavresample-dev
  - sh: sudo apt -y install x264 v4l-utils
  - su: sudo apt -y install libwebp-dev

build_script:
  - sh: cd opencv
  - sh: mkdir build
  - sh: cd build
  - sh: cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=~/build \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=OFF \
      -D BUILD_DOCS=OFF \
      -D BUILD_EXAMPLES=OFF \
      -D BUILD_TESTS=OFF \
      -D BUILD_PERF_TESTS=OFF \
      -D BUILD_opencv_apps=OFF \
      -D BUILD_opencv_datasets=OFF \
      -D BUILD_opencv_java_bindings_generator=OFF \
      -D BUILD_opencv_python_bindings_generator=OFF \
      -D BUILD_opencv_ts=OFF \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=OFF \
      -D WITH_OPENGL=ON \
      -D OPENCV_ENABLE_NONFREE=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D BUILD_SHARED_LIBS=OFF \
  - sh: make -j4
  - sh: make install

artifacts: build
