name: Windows Server 2019

on:
  pull_request:
    types: [synchronize, opened]

env:
  OPENCV_VERSION: 4.5.2

jobs:
  build:

    strategy:
      matrix:
        platform: ["win", "uwp"]
        arch: ["x86", "x64", "ARM"]
        exclude:
          - platform: win
            arch: ARM

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Server-Media-Foundation
        shell: powershell
        run: |
          Install-WindowsFeature Server-Media-Foundation

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

#      - name: Vcpkg
#        shell: powershell
#        if: ${{ matrix.platform == 'win' }}
#        run: |
#          vcpkg version
#          vcpkg install tesseract:${{matrix.arch}}-windows-static
#          vcpkg integrate install
#          vcpkg list

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v6
        if: ${{ matrix.platform == 'win' }}
        with:
          setupOnly: true
          #vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5 # tag:2020.11-1
          vcpkgGitCommitId: 9231937a9a2b57f4bda7a724af4f3743ace81cc0
          vcpkgGitURL: https://github.com/shimat/vcpkg.git

      - name: Vcpkg
        shell: powershell
        if: ${{ matrix.platform == 'win' }}
        run: |
          echo ${env:VCPKG_ROOT}
          ls ${env:VCPKG_ROOT}
          & ${env:VCPKG_ROOT}\vcpkg install tesseract:${{matrix.arch}}-windows-static
          & ${env:VCPKG_ROOT}\vcpkg integrate install
          & ${env:VCPKG_ROOT}\vcpkg list
          ls ${env:VCPKG_ROOT}\installed
          ls ${env:VCPKG_ROOT}\installed\${{matrix.arch}}-windows-static
          ls ${env:VCPKG_ROOT}\installed\${{matrix.arch}}-windows-static\include
          ls ${env:VCPKG_ROOT}\installed\${{matrix.arch}}-windows-static\lib

      - name: Build
        shell: powershell
        run: |
          if ("${{matrix.platform}}" -eq 'win'){
            . ".\build_windows.ps1"
            BuildForWindows ${{matrix.arch}} "${env:VCPKG_ROOT}" $TRUE
          }
          elseif ("${{matrix.platform}}" -eq 'uwp'){
            . ".\build_uwp.ps1"
            BuildForUWP ${{matrix.arch}} "${env:VCPKG_ROOT}" $TRUE
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts_${{matrix.platform}}-${{matrix.arch}}
          path: build_${{matrix.platform}}_${{matrix.arch}}/install
